CREATE TABLE usuarios (

       id BIGINT NOT NULL AUTO_INCREMENT,
       login VARCHAR(50) NOT NULL UNIQUE,
       senha VARCHAR(150) NOT NULL,
       ativo TINYINT NOT NULL DEFAULT 1,
       perfil VARCHAR (15) NOT NULL DEFAULT "USER",

    PRIMARY KEY(id)
);